import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/SmoothScroll";
import { MyProvider } from "./context/Context";

const geistSans = Geist({
  variable: "--font-geist-sans",
});

export const metadata: Metadata = {
  title: "Essentia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable}  h-full antialiased`}>
      <body className="min-h-full flex flex-col">
          <MyProvider>
            <SmoothScroll>{children}</SmoothScroll>
          </MyProvider>
      </body>
    </html>
  );
}
